### PR TITLE
Ticket 1757 Added methods to convert time

### PR DESCRIPTION
**Pull request by morgandavies1997**
Added methods to convert the 'old_value' to 'hrs, min, s'

### CODE REVIEW

**Comment by Tom-Willemsen** [comment]
Hi Morgan,

This change looks fine, but can I suggest using Python's library functions for this? It's better to use library functions if they exist because they are typically less error-prone than writing your own functions.

For this particular problem, you could use something like [python's datetime library](https://docs.python.org/2/library/datetime.html#datetime.timedelta), like this:
```
formatted_time = str(datetime.timedelta(seconds=number_of_seconds))
```
which will return a time formatted as `h:mm:ss`.

If you're unsure about what I mean, please feel free to ask!

**Comment by morgandavies1997** [comment]
The reason why we are using the calculations, is because there is no easier way for calculating the time in (hrs, min ,s) with 'timedelta' and wanted to keep the format to match the time on the GUI

**Comment by Tom-Willemsen** [comment]
Hi again Morgan,

At the moment, your code isn't working properly with values of less than 60 seconds.

In your first if-else block, you set the value correctly for values of less than 60 seconds:
```
if int(old_value) < 60:
    # The following line sets the value correctly:
    block.set_value(old_value + " s")
else:
    minutes = int(old_value) / 60
    seconds = int(old_value) % 60
```
but in your second if-else block, you overwrite the correct value with an incorrect one:
```
if minutes < 60:
    # The following line overwrites the correct value (if old_value < 60)
    block.set_value(str(minutes) + " min " + str(seconds) + " s") 
else:
    hours = minutes / 60
    minutes %= 60
    block.set_value(str(hours) + " hr " + str(minutes) + " min " + str(seconds) + " s")
```
There are a number of approaches that you could use to fix this issue; The simplest approach would be to use the `return` keyword after you've set the value the first time, so that your first if-else block looks like this:
```
if int(old_value) < 60:
    block.set_value(old_value + " s")
    return
else:
    minutes = int(old_value) / 60
    seconds = int(old_value) % 60
```
...but it might be neater to do something like this:
```
# Find number of hours, minutes, seconds using your preferred method...

if hours == 0 and minutes == 0:
   set_block_value(seconds + "s")
elif hours == 0:
    set_block_value(minutes + " min " + seconds + " s")
else:
    set_block_value(hours+ " hr " + minutes + " min " + seconds + " s")
```

**Comment by Tom-Willemsen** [comment]
Hi Morgan, this is all ok now.

Could you just remove the `.pyc` file you accidentally committed, and then I will merge this.

**Pull request merged**
